<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Mathematics\NovoDwarf.Mathematics.Core\NovoDwarf.Mathematics.Core.csproj" />
      <ProjectReference Include="..\..\Mathematics\NovoDwarf.Mathematics.Probability\NovoDwarf.Mathematics.Probability.csproj" />
      <ProjectReference Include="..\NovoDwarf.Modeling.Core\NovoDwarf.Modeling.Core.csproj" />
      <ProjectReference Include="..\NovoDwarf.Modeling.EventDriven\NovoDwarf.Modeling.EventDriven.csproj" />
    </ItemGroup>

</Project>
