<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DocumentationFile>bin\Debug\Mathematics.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\Mathematics.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Utilities\Utilities.csproj" />
      <ProjectReference Include="..\Mathematics.SourceGenerators\Mathematics.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Distributions.Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Distribution.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Functions.Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Functions.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Distributions.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Distributions.Resources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Functions.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Functions.Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    </ItemGroup>

</Project>
