using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mathematics.SourceGenerators;

[Generator]
public class DistributionCategoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;
        
        if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;
        
        return IsDistributionSubclass(classSymbol) ? classSymbol : null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes, SourceProductionContext context)
    {
        foreach (var classSymbol in classes)
        {
            if (classSymbol is null)
                continue;
            
            try
            {
                var sourceCode = GenerateCategoryProperties(classSymbol);
                context.AddSource($"{classSymbol.Name}.Category.g.cs", sourceCode);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "MSG002",
                        "Error generating category properties",
                        "Error generating category properties for {0}: {1}",
                        "Generation",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None,
                    classSymbol.Name,
                    ex.Message));
            }
        }
    }

    private static string GenerateCategoryProperties(INamedTypeSymbol classSymbol)
    {
        var className = classSymbol.Name;
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        
        // Определяем категорию и подкатегорию на основе namespace
        var (category, subCategory) = DetermineCategoriesFromNamespace(namespaceName);

        return $$"""
                 // <auto-generated/>
                 
                 using Mathematics.Distributions.Enums;
                 
                 namespace {{namespaceName}}
                 {
                     public partial class {{className}}
                     {
                         public override DistributionCategory Category => {{category}};
                         public override DistributionSubCategory SubCategory => {{subCategory}};
                     }
                 }
                 """;
    }

    private static (string category, string subCategory) DetermineCategoriesFromNamespace(string namespaceName)
    {
        // TODO: rework this
        
        return ("DistributionCategory.Unknown", "DistributionSubCategory.Unknown");
    }
    
    private static bool IsDistributionSubclass(INamedTypeSymbol classSymbol)
    {
        var baseType = classSymbol.BaseType;
       
        while (baseType != null)
        {
            if (baseType.Name == "Distribution")
                return true;
            
            baseType = baseType.BaseType;
        }
        
        return false;
    }
}