using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mathematics.SourceGenerators;

[Generator]
public class PropertiesGenerator : IIncrementalGenerator
{
    private static readonly List<string> ClassSuffixes = 
    [
        "Distribution", "Function"
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsSyntaxTargetForGeneration(node),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());
        
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node) => node is ClassDeclarationSyntax;

    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;
        
        if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;
        
        if (!IsEntitySubclass(classSymbol))
            return null;
        
        if (!HasValidSuffix(classSymbol.Name))
            return null;

        return classSymbol;
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes, SourceProductionContext context)
    {
        foreach (var classSymbol in Enumerable.OfType<INamedTypeSymbol>(classes))
        {
            try
            {
                var sourceCode = GenerateProperties(classSymbol);
                context.AddSource($"{classSymbol.Name}.g.cs", sourceCode);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "MSG001",
                        "Error generating properties",
                        "Error generating properties for {0}: {1}",
                        "Generation",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None,
                    classSymbol.Name,
                    ex.Message));
            }
        }
    }

    private static string GenerateProperties(INamedTypeSymbol classSymbol)
    {
        var className = classSymbol.Name;
        var distributionName = GetName(className);
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

        return $$"""
                 // <auto-generated/>
                 using System;

                 namespace {{namespaceName}}
                 {
                     public partial class {{className}}
                     {
                         private static readonly string _distributionName = "{{distributionName}}";
                         
                         public override string Name => _distributionName + "_name";
                         public override string Description => _distributionName + "_desc";
                     }
                 }
                 """;
    }

    private static bool IsEntitySubclass(INamedTypeSymbol classSymbol)
    {
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (string.Equals(baseType.Name, "Entity", StringComparison.OrdinalIgnoreCase))
                return true;
            
            baseType = baseType.BaseType;
        }
        return false;
    }

    private static bool HasValidSuffix(string className)
    {
        return ClassSuffixes.Any(suffix => 
            className.EndsWith(suffix) && className.Length > suffix.Length);
    }

    private static string GetName(string name)
    {
        return ClassSuffixes
            .Aggregate(name, (current, suffix) => current.Replace(suffix, string.Empty))
            .ToLowerInvariant();
    }
}