<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Grekov\Grekov\Grekov.csproj" />
      <ProjectReference Include="..\..\Komissar\Komissar\Komissar.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Friflo.Engine.ECS" Version="4.0.0-preview.2" />
      <PackageReference Include="Friflo.Engine.ECS.Boost" Version="4.0.0-preview.2" />
    </ItemGroup>

</Project>
