<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0"/>
        <PackageReference Include="ImGui.NET.DirectX" Version="1.75.1"/>
        <PackageReference Include="Messager.NET" Version="1.0.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.AutoActivation" Version="10.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-rc.2.25502.107"/>
        <PackageReference Include="Serilog.Enrichers.CallerInfo" Version="1.0.6"/>
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.1-dev-02307"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Silk.NET" Version="2.22.0"/>
        <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.22.0"/>
        <PackageReference Include="Silk.NET.Direct3D11" Version="2.22.0"/>
        <PackageReference Include="Silk.NET.Windowing" Version="2.22.0"/>
        <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0"/>
        <PackageReference Include="Silk.NET.Input" Version="2.22.0"/>
    </ItemGroup>
    
    <ItemGroup>
        <Folder Include="UI\"/>
    </ItemGroup>

</Project>
