<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Mathematics.Numerical</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NovoDwarf.Mathematics.Core\NovoDwarf.Mathematics.Core.csproj" />
    </ItemGroup>

</Project>
