//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mathematics.App.Maui.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Measurement_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Measurement_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mathematics.App.Maui.Resources.Localizations.Measurement.Resources", typeof(Measurement_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        internal static string Measurement_Acceleration {
            get {
                return ResourceManager.GetString("Measurement_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Measurement_Amount {
            get {
                return ResourceManager.GetString("Measurement_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Measurement_Current {
            get {
                return ResourceManager.GetString("Measurement_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Measurement_Energy {
            get {
                return ResourceManager.GetString("Measurement_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        internal static string Measurement_Force {
            get {
                return ResourceManager.GetString("Measurement_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Measurement_Frequency {
            get {
                return ResourceManager.GetString("Measurement_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Measurement_Length {
            get {
                return ResourceManager.GetString("Measurement_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminous Intensity.
        /// </summary>
        internal static string Measurement_LuminousIntensity {
            get {
                return ResourceManager.GetString("Measurement_LuminousIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string Measurement_Mass {
            get {
                return ResourceManager.GetString("Measurement_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Measurement_Pressure {
            get {
                return ResourceManager.GetString("Measurement_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Measurement_Speed {
            get {
                return ResourceManager.GetString("Measurement_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Measurement_Temperature {
            get {
                return ResourceManager.GetString("Measurement_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Measurement_Time {
            get {
                return ResourceManager.GetString("Measurement_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Measurement_Volume {
            get {
                return ResourceManager.GetString("Measurement_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical.
        /// </summary>
        internal static string MeasurementSystem_Astronomical {
            get {
                return ResourceManager.GetString("MeasurementSystem_Astronomical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MeasurementSystem_CGS {
            get {
                return ResourceManager.GetString("MeasurementSystem_CGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        internal static string MeasurementSystem_Imperial {
            get {
                return ResourceManager.GetString("MeasurementSystem_Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MeasurementSystem_MKS {
            get {
                return ResourceManager.GetString("MeasurementSystem_MKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MeasurementSystem_Natural {
            get {
                return ResourceManager.GetString("MeasurementSystem_Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planck.
        /// </summary>
        internal static string MeasurementSystem_Planck {
            get {
                return ResourceManager.GetString("MeasurementSystem_Planck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI (System International).
        /// </summary>
        internal static string MeasurementSystem_SI {
            get {
                return ResourceManager.GetString("MeasurementSystem_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MeasurementSystem_USCustomary {
            get {
                return ResourceManager.GetString("MeasurementSystem_USCustomary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atto.
        /// </summary>
        internal static string Prefix_Atto {
            get {
                return ResourceManager.GetString("Prefix_Atto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centi.
        /// </summary>
        internal static string Prefix_Centi {
            get {
                return ResourceManager.GetString("Prefix_Centi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deca.
        /// </summary>
        internal static string Prefix_Deca {
            get {
                return ResourceManager.GetString("Prefix_Deca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deci.
        /// </summary>
        internal static string Prefix_Deci {
            get {
                return ResourceManager.GetString("Prefix_Deci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exa.
        /// </summary>
        internal static string Prefix_Exa {
            get {
                return ResourceManager.GetString("Prefix_Exa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to femto.
        /// </summary>
        internal static string Prefix_Femto {
            get {
                return ResourceManager.GetString("Prefix_Femto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giga.
        /// </summary>
        internal static string Prefix_Giga {
            get {
                return ResourceManager.GetString("Prefix_Giga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hecto.
        /// </summary>
        internal static string Prefix_Hecto {
            get {
                return ResourceManager.GetString("Prefix_Hecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilo.
        /// </summary>
        internal static string Prefix_Kilo {
            get {
                return ResourceManager.GetString("Prefix_Kilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mega.
        /// </summary>
        internal static string Prefix_Mega {
            get {
                return ResourceManager.GetString("Prefix_Mega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to micro.
        /// </summary>
        internal static string Prefix_Micro {
            get {
                return ResourceManager.GetString("Prefix_Micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli.
        /// </summary>
        internal static string Prefix_Milli {
            get {
                return ResourceManager.GetString("Prefix_Milli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nano.
        /// </summary>
        internal static string Prefix_Nano {
            get {
                return ResourceManager.GetString("Prefix_Nano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prefix_None {
            get {
                return ResourceManager.GetString("Prefix_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peta.
        /// </summary>
        internal static string Prefix_Peta {
            get {
                return ResourceManager.GetString("Prefix_Peta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pico.
        /// </summary>
        internal static string Prefix_Pico {
            get {
                return ResourceManager.GetString("Prefix_Pico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quecto.
        /// </summary>
        internal static string Prefix_Quecto {
            get {
                return ResourceManager.GetString("Prefix_Quecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quetta.
        /// </summary>
        internal static string Prefix_Quetta {
            get {
                return ResourceManager.GetString("Prefix_Quetta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ronna.
        /// </summary>
        internal static string Prefix_Ronna {
            get {
                return ResourceManager.GetString("Prefix_Ronna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ronto.
        /// </summary>
        internal static string Prefix_Ronto {
            get {
                return ResourceManager.GetString("Prefix_Ronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tera.
        /// </summary>
        internal static string Prefix_Tera {
            get {
                return ResourceManager.GetString("Prefix_Tera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yocto.
        /// </summary>
        internal static string Prefix_Yocto {
            get {
                return ResourceManager.GetString("Prefix_Yocto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yotta.
        /// </summary>
        internal static string Prefix_Yotta {
            get {
                return ResourceManager.GetString("Prefix_Yotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zepto.
        /// </summary>
        internal static string Prefix_Zepto {
            get {
                return ResourceManager.GetString("Prefix_Zepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zetta.
        /// </summary>
        internal static string Prefix_Zetta {
            get {
                return ResourceManager.GetString("Prefix_Zetta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ampere.
        /// </summary>
        internal static string Unit_Ampere {
            get {
                return ResourceManager.GetString("Unit_Ampere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Atmosphere {
            get {
                return ResourceManager.GetString("Unit_Atmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Bar {
            get {
                return ResourceManager.GetString("Unit_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Calorie {
            get {
                return ResourceManager.GetString("Unit_Calorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candela.
        /// </summary>
        internal static string Unit_Candela {
            get {
                return ResourceManager.GetString("Unit_Candela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string Unit_Celsius {
            get {
                return ResourceManager.GetString("Unit_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Day {
            get {
                return ResourceManager.GetString("Unit_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Dyne {
            get {
                return ResourceManager.GetString("Unit_Dyne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        internal static string Unit_Fahrenheit {
            get {
                return ResourceManager.GetString("Unit_Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot.
        /// </summary>
        internal static string Unit_Foot {
            get {
                return ResourceManager.GetString("Unit_Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Gallon {
            get {
                return ResourceManager.GetString("Unit_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        internal static string Unit_Gram {
            get {
                return ResourceManager.GetString("Unit_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Hertz {
            get {
                return ResourceManager.GetString("Unit_Hertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Hour {
            get {
                return ResourceManager.GetString("Unit_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        internal static string Unit_Inch {
            get {
                return ResourceManager.GetString("Unit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Joule {
            get {
                return ResourceManager.GetString("Unit_Joule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        internal static string Unit_Kelvin {
            get {
                return ResourceManager.GetString("Unit_Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_KilometerPerHour {
            get {
                return ResourceManager.GetString("Unit_KilometerPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_KilowattHour {
            get {
                return ResourceManager.GetString("Unit_KilowattHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Knot {
            get {
                return ResourceManager.GetString("Unit_Knot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Liter {
            get {
                return ResourceManager.GetString("Unit_Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string Unit_Meter {
            get {
                return ResourceManager.GetString("Unit_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter per second.
        /// </summary>
        internal static string Unit_MeterPerSecond {
            get {
                return ResourceManager.GetString("Unit_MeterPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter per second squared.
        /// </summary>
        internal static string Unit_MeterPerSecondSquared {
            get {
                return ResourceManager.GetString("Unit_MeterPerSecondSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile.
        /// </summary>
        internal static string Unit_Mile {
            get {
                return ResourceManager.GetString("Unit_Mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_MilePerHour {
            get {
                return ResourceManager.GetString("Unit_MilePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_MillimeterOfMercury {
            get {
                return ResourceManager.GetString("Unit_MillimeterOfMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Minute {
            get {
                return ResourceManager.GetString("Unit_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mole.
        /// </summary>
        internal static string Unit_Mole {
            get {
                return ResourceManager.GetString("Unit_Mole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Mile.
        /// </summary>
        internal static string Unit_NauticalMile {
            get {
                return ResourceManager.GetString("Unit_NauticalMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newton.
        /// </summary>
        internal static string Unit_Newton {
            get {
                return ResourceManager.GetString("Unit_Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounce.
        /// </summary>
        internal static string Unit_Ounce {
            get {
                return ResourceManager.GetString("Unit_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Pascal {
            get {
                return ResourceManager.GetString("Unit_Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        internal static string Unit_Pound {
            get {
                return ResourceManager.GetString("Unit_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_PoundForce {
            get {
                return ResourceManager.GetString("Unit_PoundForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_PSI {
            get {
                return ResourceManager.GetString("Unit_PSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_Quart {
            get {
                return ResourceManager.GetString("Unit_Quart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Unit_RevolutionsPerMinute {
            get {
                return ResourceManager.GetString("Unit_RevolutionsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Unit_Second {
            get {
                return ResourceManager.GetString("Unit_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        internal static string Unit_Slug {
            get {
                return ResourceManager.GetString("Unit_Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard.
        /// </summary>
        internal static string Unit_Yard {
            get {
                return ResourceManager.GetString("Unit_Yard", resourceCulture);
            }
        }
    }
}
