<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Mathematics.Cryptography</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="HashFunctions\" />
      <Folder Include="Monosound\" />
      <Folder Include="Polyalphabet\" />
      <Folder Include="Polygramms\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NovoDwarf.Mathematics.Core\NovoDwarf.Mathematics.Core.csproj" />
    </ItemGroup>

</Project>
