using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using Mathematics.SourceGenerators.Utilities;

namespace Mathematics.SourceGenerators.Generators.Distributions;

[Generator]
public class DistributionConstructorGenerator : IIncrementalGenerator
{
    private const string DictionaryType = "Dictionary<string, string>";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidateClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateClass(s),
                transform: static (ctx, _) => GetValidClassDeclaration(ctx))
            .Where(static classDecl => classDecl is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(candidateClasses.Collect());
        
        context.RegisterSourceOutput(
            compilationAndClasses, 
            static (context, source) => Execute(context, source.Left, source.Right));
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl && 
               HasParameterizedConstructor(classDecl) && 
               HasBaseTypes(classDecl);
    }

    private static bool HasParameterizedConstructor(ClassDeclarationSyntax classDecl)
    {
        return classDecl.Members
            .OfType<ConstructorDeclarationSyntax>()
            .Any(constructor => constructor.ParameterList.Parameters.Count > 0);
    }

    private static bool HasBaseTypes(ClassDeclarationSyntax classDecl)
    {
        return classDecl.BaseList?.Types.Count > 0;
    }

    private static ClassDeclarationSyntax? GetValidClassDeclaration(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        
        if (HasDictionaryConstructor(classDecl))
            return null;

        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDecl);
        
        return GeneratorUtils.IsDistributionSubclass(classSymbol) ? classDecl : null;
    }

    private static bool HasDictionaryConstructor(ClassDeclarationSyntax classDecl)
    {
        return classDecl.Members
            .OfType<ConstructorDeclarationSyntax>()
            .Any(constructor => constructor.ParameterList.Parameters
                .Any(parameter => parameter.Type?.ToString() == DictionaryType));
    }


    private static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<ClassDeclarationSyntax?> classes)
    {
        foreach (var classDecl in Enumerable.OfType<ClassDeclarationSyntax>(classes))
        {
            try
            {
                GenerateConstructor(context, compilation, classDecl);
            }
            catch (Exception ex)
            {
                ReportGenerationError(context, classDecl, ex);
            }
        }
    }

    private static void GenerateConstructor(SourceProductionContext context, Compilation compilation, ClassDeclarationSyntax classDecl)
    {
        var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
        
        if (semanticModel.GetDeclaredSymbol(classDecl) is not { } classSymbol)
            return;

        var primaryConstructor = GetPrimaryConstructor(classDecl);
        if (primaryConstructor is null) return;

        var sourceCode = GenerateConstructorSource(classSymbol, primaryConstructor, semanticModel);
        var fileName = $"{classSymbol.Name}_DictionaryConstructor.g.cs";
        
        context.AddSource(fileName, SourceText.From(sourceCode, Encoding.UTF8));
    }

    private static ConstructorDeclarationSyntax? GetPrimaryConstructor(ClassDeclarationSyntax classDecl)
    {
        return classDecl.Members
            .OfType<ConstructorDeclarationSyntax>()
            .FirstOrDefault(constructor => constructor.ParameterList.Parameters.Count > 0);
    }

    private static string GenerateConstructorSource(
        INamedTypeSymbol classSymbol,
        ConstructorDeclarationSyntax constructor,
        SemanticModel semanticModel)
    {
        var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty;
        var className = classSymbol.Name;
        var parameterAssignments = GenerateParameterAssignments(constructor, semanticModel);

        return $$"""
            // <auto-generated/>
            #nullable enable

            {{GetNamespaceDeclaration(namespaceName)}}
            public partial class {{className}}
            {
                public {{className}}(System.Collections.Generic.Dictionary<string, string> parameters)
                {
            {{parameterAssignments}}
                }
            }
            """;
    }

    private static string GetNamespaceDeclaration(string namespaceName)
    {
        return string.IsNullOrWhiteSpace(namespaceName) 
            ? string.Empty 
            : $"namespace {namespaceName};\n\n";
    }

    private static string GenerateParameterAssignments(
        ConstructorDeclarationSyntax constructor, 
        SemanticModel semanticModel)
    {
        var assignments = constructor.ParameterList.Parameters
            .Select(parameter => GenerateParameterAssignment(parameter, semanticModel))
            .Where(assignment => !string.IsNullOrEmpty(assignment));

        return string.Join("\n            ", assignments);
    }

    private static string GenerateParameterAssignment(
        ParameterSyntax parameter, 
        SemanticModel semanticModel)
    {
        var parameterName = parameter.Identifier.ValueText;
        var parameterType = parameter.Type?.ToString() ?? "object";
        var parameterSymbol = semanticModel.GetDeclaredSymbol(parameter);

        return parameterSymbol?.Type is not { } typeSymbol 
            ? $"_{parameterName} = {ParseUtils.Parse(parameterName, parameterType)};" 
            : GenerateTypedParameterAssignment(parameterName, typeSymbol);
    }

    private static string GenerateTypedParameterAssignment(string parameterName, ITypeSymbol typeSymbol)
    {
        var typeName = typeSymbol.ToDisplayString();
        var conversionCode = ParseUtils.Parse($"parameters[\"{parameterName}\"]", typeName, typeSymbol);
        
        return $"_{parameterName} = {conversionCode};";
    }

    private static void ReportGenerationError(
        SourceProductionContext context,
        ClassDeclarationSyntax classDecl,
        Exception exception)
    {
        var diagnostic = Diagnostic.Create(
            DiagnosticUtils.ErrorGeneratingDistributionConstructor(),
            Location.None,
            classDecl.Identifier.ValueText,
            exception.Message);
        
        context.ReportDiagnostic(diagnostic);
    }
}