<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Search\" />
      <Folder Include="Sorting\" />
      <Folder Include="Transformation\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mathematics.Core\Mathematics.Core.csproj" />
    </ItemGroup>

</Project>
