<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
        
        <OutputType>Exe</OutputType>
        <RootNamespace>Mathematics.App</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <EnableUnsafeBlocks>true</EnableUnsafeBlocks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
        <MauiStrictXamlCompilation>true</MauiStrictXamlCompilation>
        <LangVersion>preview</LangVersion>
        <UseMaterial3>true</UseMaterial3>

        <!-- Display name -->
        <ApplicationTitle>Mathematics.App.Maui</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.novodwarf.mathematics.app.maui</ApplicationId>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>

        <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
        <WindowsPackageType>None</WindowsPackageType>
        
        <AndroidSdkDirectory>D:\Program Files\AndroidSdk</AndroidSdkDirectory>
        
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">35.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4"/>

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128"/>

        <!-- Images -->
        <MauiImage Include="Resources\Images\*"/>
        <MauiImage Include="Resources\Images\Pages\*"/>
        <MauiImage Include="Resources\Images\Utilities\*"/>

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*"/>

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AdamE.MemoryToolkit.Maui" Version="1.0.0" />
        <PackageReference Include="Plugin.Maui.Audio" Version="4.0.0" />
        <PackageReference Include="AiForms.Maui.SettingsView" Version="9.0.5-pre" />
        <PackageReference Include="Camera.MAUI.ZXing" Version="1.0.0" />
        <PackageReference Include="CommunityToolkit.Maui" Version="13.0.0" />
        <PackageReference Include="NCalcAsync" Version="5.11.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc6.1" />
        <PackageReference Include="LocalizationResourceManager.Maui" Version="1.3.0-alpha.4" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.20" />
        <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.20" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.1" />
        <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
        <PackageReference Include="Serilog.Enrichers.CallerInfo" Version="1.0.6" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="ZXing.Net.Maui" Version="0.7.2" />
        <PackageReference Include="ZXing.Net.Maui.Controls" Version="0.7.2" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Mathematics.Core\Mathematics.Core.csproj" />
      <ProjectReference Include="..\Mathematics.DependencyInjection\Mathematics.DependencyInjection.csproj" />
      <ProjectReference Include="..\Mathematics.Graphics\Mathematics.Graphics.csproj" />
      <ProjectReference Include="..\Mathematics.Processing\Mathematics.Processing.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <EmbeddedResource Update="Resources\Localizations\Components.Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Components.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Localizations\Measurement.Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Measurement.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
    
    <ItemGroup>
      <Compile Update="UI\Views\Common\ParameterView.xaml.cs">
        <DependentUpon>ParameterView.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Distributions\DistributionPage.xaml.cs">
        <DependentUpon>DistributionView.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Pages\Algorithms\CompressionsPage.xaml.cs">
        <DependentUpon>CompressionsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Pages\Algorithms\CryptographyPage.xaml.cs">
        <DependentUpon>CryptographyPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Pages\Algorithms\ProbabilityPage.xaml.cs">
        <DependentUpon>DistributionsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Pages\Algorithms\NumericalPage.xaml.cs">
        <DependentUpon>FunctionsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Pages\Algorithms\GraphicsPage.xaml.cs">
        <DependentUpon>GraphicsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Pages\Algorithms\SortingPage.xaml.cs">
        <DependentUpon>SortingsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Resources\Localizations\Components.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Components.Resources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Localizations\Measurement.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Measurement.Resources.resx</DependentUpon>
      </Compile>
      <Compile Update="UI\Views\Graphics\Drawings\CirclesDrawPage.xaml.cs">
        <DependentUpon>CircleDrawPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Graphics\Drawings\FillDrawPage.xaml.cs">
        <DependentUpon>FillDrawPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Graphics\Drawings\LineDrawPage.xaml.cs">
        <DependentUpon>LineDrawPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Sensors\AccelerometerPage.xaml.cs">
        <DependentUpon>AccelerometerPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Sensors\BarometerPage.xaml.cs">
        <DependentUpon>BarometerPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Sensors\CompassPage.xaml.cs">
        <DependentUpon>CompassPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Sensors\DeviceInfoPage.xaml.cs">
        <DependentUpon>DeviceInfoPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Sensors\FlashlightPage.xaml.cs">
        <DependentUpon>FlashlightPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Sensors\SpeedometerPage.xaml.cs">
        <DependentUpon>SpeedometerPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Organizers\TimerPage.xaml.cs">
        <DependentUpon>TimerPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Organizers\StopwatchPage.xaml.cs">
        <DependentUpon>StopwatchPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Organizers\NotesPage.xaml.cs">
        <DependentUpon>NotesPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Organizers\ConverterPage.xaml.cs">
        <DependentUpon>ConverterPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\CalculatorPage.xaml.cs">
        <DependentUpon>CalculatorPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\CashCalculatorPage.xaml.cs">
        <DependentUpon>CashCalculatorPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\CodeGeneratorPage.xaml.cs">
        <DependentUpon>CodeGeneratorPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\CodeScannerPage.xaml.cs">
        <DependentUpon>CodeScannerPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\LevelPage.xaml.cs">
        <DependentUpon>LevelPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\MirrorPage.xaml.cs">
        <DependentUpon>MirrorPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\RulerPage.xaml.cs">
        <DependentUpon>RulerPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\SoundGeneratorPage.xaml.cs">
        <DependentUpon>SoundGeneratorPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Tools\SynthPage.xaml.cs">
        <DependentUpon>SynthPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Utilities\Sensors\SoundmeterPage.xaml.cs">
        <DependentUpon>SoundmeterPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Probability\Distributions\DistributionPage.xaml.cs">
        <DependentUpon>DistributionPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="UI\Views\Probability\Distributions\DistributionPlotView.xaml.cs">
        <DependentUpon>DistributionPlotView.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\AboutPage.xaml.cs">
        <DependentUpon>AboutPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\ModulesPage.xaml.cs">
        <DependentUpon>AlgorithmsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\DebugPage.xaml.cs">
        <DependentUpon>DebugPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\MainPage.xaml.cs">
        <DependentUpon>MainPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\SettingsPage.xaml.cs">
        <DependentUpon>SettingsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\GamesPage.xaml.cs">
        <DependentUpon>GamesPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\CompressionsPage.xaml.cs">
        <DependentUpon>CompressionsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\CryptographyPage.xaml.cs">
        <DependentUpon>CryptographyPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\ProbabilityPage.xaml.cs">
        <DependentUpon>ProbabilityPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\NumericalPage.xaml.cs">
        <DependentUpon>NumericalPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\GraphicsPage.xaml.cs">
        <DependentUpon>GraphicsPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\SortingPage.xaml.cs">
        <DependentUpon>SortingPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Modules\UtilityPage.xaml.cs">
        <DependentUpon>UtilityPage.xaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
    
    <ItemGroup>
      <MauiXaml Update="UI\Views\Common\ParameterView.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Distributions\DistributionPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Pages\Algorithms\CompressionsPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Pages\Algorithms\CryptographyPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Pages\Algorithms\ProbabilityPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Pages\Algorithms\NumericalPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Pages\Algorithms\GraphicsPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Pages\Algorithms\SortingPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Graphics\Drawings\CirclesDrawPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Graphics\Drawings\FillDrawPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Graphics\Drawings\LineDrawPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Sensors\AccelerometerPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Sensors\BarometerPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Sensors\CompassPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Sensors\DeviceInfoPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Sensors\FlashlightPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Sensors\SpeedometerPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Organizers\TimerPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Organizers\StopwatchPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Organizers\NotesPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Organizers\ConverterPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\CalculatorPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\CashCalculatorPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\CodeGeneratorPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\CodeScannerPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\LevelPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\MirrorPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\RulerPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\SoundGeneratorPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Tools\SynthPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Utilities\Sensors\SoundmeterPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Probability\Distributions\DistributionPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="UI\Views\Probability\Distributions\DistributionPlotView.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\AboutPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\ModulesPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\DebugPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\MainPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\SettingsPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\GamesPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\CompressionsPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\CryptographyPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\ProbabilityPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\NumericalPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\GraphicsPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\SortingPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
      <MauiXaml Update="Views\Modules\UtilityPage.xaml">
        <SubType>Designer</SubType>
      </MauiXaml>
    </ItemGroup>
    
    <ItemGroup>
      <Reference Include="SettingsView">
        <HintPath>C:\Users\kiril\.nuget\packages\aiforms.maui.settingsview\9.0.5-pre\lib\net9.0\SettingsView.dll</HintPath>
      </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <AdditionalFiles Include="Views\Common\HeaderView.xaml" />
      <AdditionalFiles Include="Views\Common\ParameterView.xaml" />
      <AdditionalFiles Include="Views\Common\PreviewSquareView.xaml" />
      <AdditionalFiles Include="Views\Common\PreviewView.xaml" />
      <AdditionalFiles Include="Views\Common\TreeNodeView.xaml" />
      <AdditionalFiles Include="Views\Modules\Games\SlidingTilePuzzlePage.xaml" />
      <AdditionalFiles Include="Views\Modules\Graphics\Drawings\CirclesDrawPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Graphics\Drawings\FillDrawPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Graphics\Drawings\LineDrawPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Graphics\Drawings\TruncationDrawPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Graphics\FractalPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Graphics\Fractals\KochCurvePage.xaml" />
      <AdditionalFiles Include="Views\Modules\Graphics\NoisesPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Numerical\FunctionPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Probability\Distributions\DistributionPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Probability\Distributions\DistributionPlotView.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Organizers\CalendarPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Organizers\ConverterPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Organizers\NotesPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Organizers\StopwatchPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Organizers\TimerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Organizers\WorldClockPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\AccelerometerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\BarometerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\CompassPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\DeviceInfoPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\FlashlightPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\GyroscopePage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\MagnetometerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\OrientationPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\SoundmeterPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Sensors\SpeedometerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\CalculatorPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\CashCalculatorPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\CodeGeneratorPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\CodeScannerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\ColorPickerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\HttpTesterPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\LevelPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\MirrorPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\RegexTesterPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\RulerPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\SoundGeneratorPage.xaml" />
      <AdditionalFiles Include="Views\Modules\Utilities\Tools\SynthPage.xaml" />
    </ItemGroup>

</Project>
