<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net11.0'">
        <PackageReference Include="Microsoft.Extensions.Logging" Version="11.0.0-rc.1.26425.128" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    </ItemGroup>

</Project>
