
namespace Mathematics.SourceGenerators.Generators;

using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class EntityParameterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classProvider = context.SyntaxProvider
            .CreateSyntaxProvider(predicate: Predicate, transform: Transform)
            .Where(static t => t.Class is not null);

        context.RegisterSourceOutput(classProvider, GenerateSource);
    }

    private static (ClassDeclarationSyntax Class, SemanticModel SemanticModel) Transform(GeneratorSyntaxContext ctx, CancellationToken token)
    {
        return (Class: (ClassDeclarationSyntax)ctx.Node, ctx.SemanticModel);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken token)
    {
        return node is ClassDeclarationSyntax classDecl && classDecl.Members.OfType<PropertyDeclarationSyntax>()
            .Any(HasEntityParameterAttribute);
    }

    private static bool HasEntityParameterAttribute(PropertyDeclarationSyntax property)
    {
        return property.AttributeLists
            .SelectMany(al => al.Attributes)
            .Any(attr => attr.Name.ToString() is "EntityParameter" or "EntityParameterAttribute");
    }
    
    private void GenerateSource(SourceProductionContext context, 
        (ClassDeclarationSyntax Class, SemanticModel SemanticModel) input)
    {
        var (classDecl, semanticModel) = input;

        if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol) 
            return;

        var entityProperties = new List<IPropertySymbol>();

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IPropertySymbol prop) 
                continue;
            
            var attrs = prop.GetAttributes();
            
            if (attrs.Any(a => a.AttributeClass?.Name is "EntityParameter" or "EntityParameterAttribute"))
                entityProperties.Add(prop);
        }
        
        if (!entityProperties.Any()) 
            return;

        var source = GenerateClassSource(classSymbol, [..entityProperties]);
        context.AddSource($"{classSymbol.Name}_EntityParameters.g.cs", source);
    }

    private SourceText GenerateClassSource(INamedTypeSymbol classSymbol, ImmutableArray<IPropertySymbol> properties)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            
            namespace {{namespaceName}};

            public partial class {{className}}
            {
                public override void Set(params object[] parameters)
                {
                    if (parameters.Length != {{properties.Length}})
                        throw new global::System.ArgumentException($"Expected {{properties.Length}} parameters, got {parameters.Length}");
            
                {{GenerateParameterConversions(properties)}}
            
                Set({{string.Join(", ", properties.Select(p => p.Name.ToLowerInvariant()))}});
                }
            
                public void Set({{GenerateTypedParameters(properties)}})
                {
                    {{GeneratePropertyAssignments(properties)}}
                    Validate();
                }
            }
            """;

        return SourceText.From(source, Encoding.UTF8);
    }

    private string GenerateParameterConversions(ImmutableArray<IPropertySymbol> properties)
    {
        var lines = new List<string>();
        
        for (var i = 0; i < properties.Length; i++)
        {
            var prop = properties[i];
            var typeName = prop.Type.ToDisplayString();
            var conversionMethod = GetConversionMethod(typeName);
            var varName = prop.Name.ToLowerInvariant();
            
            lines.Add($"        var {varName} = global::System.Convert.{conversionMethod}(parameters[{i}]);");
        }
        
        return string.Join("\n", lines);
    }

    private static string GenerateTypedParameters(ImmutableArray<IPropertySymbol> properties)
    {
        var parameters = new List<string>();
        
        foreach (var prop in properties)
        {
            var typeName = prop.Type.ToDisplayString();
            var paramName = prop.Name.ToLowerInvariant();
            parameters.Add($"{typeName} {paramName}");
        }
        
        return string.Join(", ", parameters);
    }

    private static string GeneratePropertyAssignments(ImmutableArray<IPropertySymbol> properties)
    {
        var lines = properties.Select(prop => $"        {prop.Name} = {prop.Name.ToLowerInvariant()};").ToList();

        return string.Join("\n", lines);
    }
    
    private static string GetConversionMethod(string typeName) => typeName switch
    {
        "double" => "ToDouble",
        "int" => "ToInt32",
        "float" => "ToSingle",
        "decimal" => "ToDecimal",
        "long" => "ToInt64",
        "bool" => "ToBoolean",
        "string" => "ToString",
        _ => "ToDouble"
    };
}