using System.Collections.Immutable;
using Mathematics.SourceGenerators.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mathematics.SourceGenerators.Generators;

[Generator]
public class PropertiesGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var classDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (node, _) => IsSyntaxTargetForGeneration(node),
				static (ctx, _) => GetSemanticTargetForGeneration(ctx))
			.Where(static m => m is not null);

		var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

		context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
	}

	private static bool IsSyntaxTargetForGeneration(SyntaxNode node) => node is ClassDeclarationSyntax;

	private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
	{
		var classDeclaration = (ClassDeclarationSyntax)context.Node;
		var model = context.SemanticModel;

		if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
			return null;

		if (!GeneratorUtils.IsEntitySubclass(classSymbol))
			return null;

		if (!GeneratorUtils.HasValidSuffix(classSymbol.Name))
			return null;

		return classSymbol;
	}

	private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> classes,
		SourceProductionContext context)
	{
		foreach (var classSymbol in Enumerable.OfType<INamedTypeSymbol>(classes))
		{
			try
			{
				var sourceCode = GenerateProperties(classSymbol);
				
				context.AddSource($"{classSymbol.Name}_Properties.g.cs", sourceCode);
			}
			catch (Exception ex)
			{
				var diagnostic = Diagnostic.Create(DiagnosticUtils.ErrorGenerating(), Location.None, classSymbol.Name, ex.Message);
				
				context.ReportDiagnostic(diagnostic);
			}
		}
	}

	private static string GenerateProperties(INamedTypeSymbol classSymbol)
	{
		var className = classSymbol.Name;
		var cleanName = GeneratorUtils.GetCleanName(className);
		var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

		return $$"""
		         // <auto-generated/>
		         using System;

		         namespace {{namespaceName}}
		         {
		             public partial class {{className}}
		             {
		                 private static readonly string _name = "{{cleanName}}";
		                 
		                 public override string Name => _name + "_Name";
		                 public override string Description => _name + "_Desc";
		             }
		         }
		         """;
	}
}