<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mathematics.Functions\Mathematics.Functions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Noises\Hybrid\" />
    </ItemGroup>

</Project>
