<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SmartHome.Core\SmartHome.Core.csproj" />
        <ProjectReference Include="..\SmartHome.HomeAssistant\SmartHome.HomeAssistant.csproj" />
        <ProjectReference Include="..\SmartHome.Health\SmartHome.Health.csproj" />
        <ProjectReference Include="..\SmartHome.Shared\SmartHome.Shared.csproj" />
        <ProjectReference Include="..\SmartHome.Telegram\SmartHome.Telegram.csproj" />
        <ProjectReference Include="..\SmartHome.MAX\SmartHome.MAX.csproj" />
        <ProjectReference Include="..\SmartHome.VK\SmartHome.VK.csproj" />
    </ItemGroup>

</Project>
