<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Multivariate\Continuous\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mathematics.Core\Mathematics.Core.csproj" />
      <ProjectReference Include="..\Mathematics.Functions\Mathematics.Functions.csproj" />
      <ProjectReference Include="..\Mathematics.Randoms\Mathematics.Randoms.csproj" />
      <ProjectReference Include="..\Mathematics.SourceGenerators\Mathematics.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
