<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Distributions\" />
      <Folder Include="Statistics\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mathematics.Core\Mathematics.Core.csproj" />
      <ProjectReference Include="..\Mathematics.Numerical\Mathematics.Numerical.csproj" />
    </ItemGroup>

</Project>
